[project]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Software Development :: Libraries",
]
dependencies = [
  "genkit",
  "asgiref>=3.8.1",
  "litestar>=2.15.1",
  "starlette>=0.46.1",
  "structlog>=25.2.0",
  "uvloop>=0.21.0",
  "uvicorn>=0.34.0",
]
description = "Sample implementation to exercise the Genkit multi server manager."
name = "multi-server"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"
